### ISSUE TITLE
Catridge not working

### ISSUE THREAD

**Issue by inddigital-xtech** [icebaker/sublime-nano-bots#2]
It was working fine but one day:

_Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "C:\Users\...\AppData\Roaming\Sublime Text\Packages\Nano Bots\nanobot_helpers.py", line 50, in fetch
    if cartridge['meta']['symbol']:
TypeError: string indices must be integers_

Please help me

**Comment by icebaker** [comment]
Hey, thanks for reporting the issue.

The public API was offline for some reason that I'm still investigating.

It's back now. You can check if it's up and running at this address: https://api.nbots.io

It should return something like this:
```json
{
  "project": "Nano Bots API",
  "version": "1.6.0",
  "nano-bots": {
    "version": "3.0.1",
    "specification": "3.0.0"
  },
  "documentation": "https://spec.nbots.io",
  "live-editor": "https://clinic.nbots.io",
  "github": "https://github.com/icebaker/nano-bots-api",
  "plugins": [
    "https://github.com/icebaker/obsidian-nano-bots",
    "https://github.com/icebaker/sublime-nano-bots",
    "https://github.com/icebaker/vscode-nano-bots"
  ]
}
```
